config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :record_labels, except: :index do
    resources :acts
    resources :playlists
    resources :record_deals
    resources :recordings, except: :edit
    resources :releases
  end

  resources :musicians, except: :show
  resources :songs, except: :show

  devise_scope :user do
    authenticated :user do
      root 'record_labels#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :song
  belongs_to :genre

  has_many :recording_producers, dependent: :destroy
  has_many :recording_acts, dependent: :destroy
  has_many :recording_performers, dependent: :destroy
  has_many :playlist_recordings, dependent: :destroy
  has_many :release_recordings, dependent: :destroy
  has_many :record_deal_recordings, dependent: :destroy

  # N:N with musicians, join tables being recording_producers & recording_performers
  has_many :musicians, through: :recording_producers
  has_many :musicians, through: :recording_performers
  # N:N with acts, join table being recording_acts
  has_many :acts, through: :recording_acts
  # N:N with record_deals, join table being record_deal_recordings
  has_many :record_deals, through: :record_deal_recordings

  has_one_attached :audio_file

  validates :title, presence: true

  include PgSearch::Model
  pg_search_scope :recordings_search,
                  against: :title,
                  associated_against: {
                    acts: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  def index
    if params[:query].present?
      @recordings = policy_scope(Recording).recordings_search(params[:query])
    else
      skip_policy_scope
    end
  end

  def show
    @recording = Recording.find(params[:id])
    authorize @recording
  end

  def new
    @recording = Recording.new
    authorize @recording
    @acts = policy_scope(Act)
    @songs = policy_scope(Song)
    @genres = policy_scope(Genre)
  end

  def create
    raise
  end

  def update
    @recording = Recording.find(params[:id])
    authorize @recording
    if @recording.update(title: params[:recording][:title])
      redirect_to record_label_recording_path(current_user.record_label, @recording), notice: "Recording Information Updated"
    else
      render :show
    end
  end

  private

  def recording_params
    params.require(:recording).permit(:title, :isrc, :lyrics, :au)
  end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
  # returns a string containing all the acts/artists stored as the recording acts
  def recording_acts_formatter(recording)
    acts = recording.recording_acts.map { |rec_act| rec_act.act.name }
    acts.join(', ')
  end
end

app/views/recordings/index.html.erb
<h3 class="text-center"><%= current_user.record_label.name %> Recordings</h3>
<div class="search-form">
  <%= form_tag record_label_recordings_path(current_user.record_label), method: :get do %>
    <div>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control form-control-sm mb-2",
        placeholder: "Search..."
      %>
    </div>
    <div class="flex just-cont-cent marg-16px">
      <%= submit_tag "Search" %>
    </div>
  <% end %>
</div>

<%= link_to 'Create New Recording', new_record_label_recording_path(current_user.record_label) %>

<% if @recordings %>
  <% @recordings.each do |recording| %>
    <details>
      <summary><%= "#{recording_acts_formatter(recording)} - #{recording.title}" %></summary>
      <%= link_to "#{recording.title}", record_label_recording_path(current_user.record_label, recording) %>
    </details>
  <% end %>
<% end %>

app/views/recordings/new.html.erb
<h3>New Recording</h3>

<%= simple_form_for [current_user.record_label, @recording] do |f| %>
  <div>
    <%= f.association :song, label: 'Song/Musical Work',
                              hint: "Work not in database? Add #{link_to 'here', new_song_path} before continuing".html_safe,
                              input_html: { class: 'select2' }  %>
    <%= f.input       :title, label: 'Recording Title',
                              placeholder: 'The Greatest Song in the World',
                              input_html: {class: 'full-width-input'} %>
    <%= f.association :acts,  label: 'Band/Act',
                              input_html: {
                                class: 'select2 full-width-input'
                              } %>
    <%= f.association :musicians, label: 'Performer',
                                  input_html: {
                                    class: 'select2 full-width-input'
                                  } %>
    <%= f.association :musicians, label: 'Producer',
                                  input_html: {
                                    class: 'select2 full-width-input'
                                  } %>
    <%= f.input :isrc,  label: 'ISRC',
                        placeholder: 'US-RC1-76-07839',
                        input_html: {class: 'full-width-input'} %>
    <%= f.input :lyrics, input_html: {class: 'full-width-input'} %>

    <div class="side-by-side-inputs">
      <%= f.input :bpm, label: 'BPM',
                        input_html: { value: 120, min: 50, max: 200 }%>
      <%= f.association :genre, label: 'Primary Genre' %>
    </div>

    <%= f.input :audio_file, as: :file %>

  </div>

  <div class="flex just-cont-cent">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/recordings/show.html.erb
<h2><%= recording_acts_formatter(@recording) %></h2>
<h3><%= @recording.title %></h3>
<% if current_user.admin? %>
  <%= simple_form_for [current_user.record_label, @recording], method: :patch do |f| %>

    <div class="form-inputs">
      <%= f.input :title,
                  label: false,
                  input_html: { placeholder: @recording.title } %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
<% end %>


<%= link_to 'Back to Recordings', :back %>