config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :record_labels, except: :index do
    resources :acts
    resources :playlists
    resources :record_deals
    resources :recordings, except: :edit
    resources :releases
  end

  resources :musicians, except: :show
  resources :songs, except: :show

  devise_scope :user do
    authenticated :user do
      root 'record_labels#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :song_creators, dependent: :destroy
  has_many :recordings

  # N:N with musicians, join table being song_composers
  has_many :musicians, through: :song_creators

  def song_creators_attributes=(song_creators_attributes)
    song_creators_attributes.each do |_, song_creator_attributes|
      self.song_creators.build(song_creator_attributes)
    end
  end

  validates :title, presence: true

  include PgSearch::Model
  pg_search_scope :songs_search,
                  against: %i[title iswc],
                  # associated_against: {
                  #   acts: :name,
                  #   recordings: :title
                  # },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = policy_scope(Song)
  end

  def new
    @song = Song.new
    authorize @song
    @musicians = policy_scope(Musician)
    @song.song_creators.build
  end

  def create
    raise
    @song = Song.new(song_params)
    authorize @song
    if @song.save!
      redirect_to songs_path, notice: 'Song Record Created'
    else
      render :new
    end
  end

  def update
  end

  private

  def song_params
    params.require(:song).permit(:title, :iswc, song_creators_attributes: %i[musician_id perf_share mech_share])
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/index.html.erb
<%= link_to "Create New Song", new_song_path %>
<% @songs.each do |song| %>
  <p><%= song.title %></p>
<% end %>

app/views/songs/new.html.erb
<h3>New Musical Work/Song</h3>

<%= simple_form_for @song do |f| %>
  <%= f.input :title, label: 'Work/Song Title', placeholder: 'The Greatest Song in the World' %>
  <%= f.input :iswc, label: 'ISWC', placeholder: 'T-034.524.680-1' %>
  <hr>
  <div class="creators">
    <div class="creator">
      <%= f.simple_fields_for :song_creators do |creators_form| %>
        <%= creators_form.input :musician_id,  collection: @musicians,
                                            label: 'Creator',
                                            hint: "Creator not in database? Add #{link_to 'here', new_musician_path} before continuing".html_safe,
                                            input_html: { class: 'select2' } %>
        <div class="side-by-side-inputs">
          <%= creators_form.input :perf_share, label: 'Perf. Rights Share (%)', input_html: { class: 'perf-share' } %>
          <%= creators_form.input :mech_share, label: 'Mech. Rights Share (%)', input_html: { class: 'mech-share' } %>
        </div>
      <% end %>
      <hr>
    </div>

    <% 19.times do %>
      <div class="creator hidden">
        <%= f.simple_fields_for :song_creators do |creators_form| %>
          <%= creators_form.input :musician_id,  collection: @musicians,
                                              label: 'Creator',
                                              hint: "Creator not in database? Add #{link_to 'here', new_musician_path} before continuing".html_safe,
                                              input_html: { class: 'select2' } %>
          <div class="side-by-side-inputs">
            <%= creators_form.input :perf_share, label: 'Perf. Rights Share (%)', input_html: { class: 'perf-share' } %>
            <%= creators_form.input :mech_share, label: 'Mech. Rights Share (%)', input_html: { class: 'mech-share' } %>
          </div>
        <% end %>
        <hr>
      </div>
    <% end %>

  </div>
  <i class="fas fa-plus add-fields"></i>
  <div class="flex just-cont-cent">
    <%= f.button :submit %>
  </div>
<% end %>