config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :record_labels, except: :index do
    resources :acts
    resources :playlists
    resources :record_deals
    resources :recordings, except: :edit
    resources :releases
  end

  resources :musicians, except: :show
  resources :songs, except: :show

  devise_scope :user do
    authenticated :user do
      root 'record_labels#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/record_label.rb
class RecordLabel < ApplicationRecord
  has_many :playlists, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :record_deals, dependent: :destroy

  has_many :acts, through: :record_deals
  has_many :releases, through: :record_deals

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/record_labels_controller.rb
class RecordLabelsController < ApplicationController
  def show
    @record_label = RecordLabel.find(current_user.record_label.id)
    authorize @record_label
    @releases = policy_scope(Release)
  end

  def new
    @record_label = RecordLabel.new
    authorize @record_label
  end

  def create
  end

  def edit
  end

  def update
  end

  private
end

app/helpers/record_labels_helper.rb
module RecordLabelsHelper
end

app/views/record_labels/show.html.erb
<h3><%= @record_label.name %></h3>
<ul>
  <li><%= link_to "Releases", record_label_releases_path(@record_label) %></li>
  <li><%= link_to "Recordings", record_label_recordings_path(@record_label) %></li>
  <li><%= link_to "Playlists", record_label_playlists_path(@record_label) %></li>
  <li><%= link_to "Musicians", musicians_path %></li>
</ul>